### ISSUE TITLE
power

### ISSUE THREAD

**Issue by sp00ck** [fachat/MicroPET#9]
Is possible put lipo or AA power?
mobile device CPET will be incredible. Small processor == need small power

**Comment by sp00ck** [comment]
You sugest MPet use more power than cell phone?

**Comment by fachat** [comment]
The Micro-PET R2 uses - without Ethernet or USB attached - uses 0.55A at 5V, i.e. around 2.75W.
The original PET has two power regulators, each rated at 1.5A with 5V, so between 7.5 and 15W (ignoring 12V / -5V, and monitor not included as with the Micro-PET)
So, the Micro-PET is 12 times faster, and uses around 1/3 the power - an efficiency gain of x36.

A modern smartphone seems to be using .5-1W depending on usage profile, even without screen backlight in some situation, as far as I can read e.g. from https://www.usenix.org/legacy/event/usenix10/tech/full_papers/Carroll.pdf

So, the Micro-PET does indeed use more energy than a modern smartphone, but not as much as I actually assumed. 
You could probably reduce the wattage by going to full 3.3V, but that would sacrifice the compatibility with the IEEE488 bus.

A random smartphone battery I found has 3.8V, and 8Wh (2100mAh) - so that would be about 2.1Ah at 3.8V, or around 3.8h at .55A for a Micro-PET. So I guess with this battery you could run it for about 3-4 hours - without a screen though.

A case that contains a Micro-PET and full size keyboard should provide enough space to hold two or even more of these batteries to supply the screen and extend the runtime.

Do you have a suggestion for a nice VGA-compatible mobile display with low power consumption?

**Comment by sp00ck** [comment]
Many thanks. Very interesting information.
